kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ default .Release.Name .Values.persistence.claimName }}
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app: "{{ .Release.Name }}"
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
