apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: "ClusterIP"
  ports:
  - port: 8888
    name: app
  selector:
    app: {{ .Release.Name }}
