# For all pgbouncer config, please check https://www.pgbouncer.org/config.html
# Deployment values for pgbouncer
replicaCount: 1
internalPort: 5432
servicePort: 5432
antiAffinity: soft
nodeAffinity: {} # optionally define nodeAffinity
tolerations: [] # optionally define tolerations
nodeSelector: {} # optionally define nodeSelector

budget:
  # PodDisruptionBudget spec.minAvailable
  minAvailable: 0

image:
  repository: bitnami/pgbouncer
  tag: 1.18.0
  pullPolicy: IfNotPresent

imagePullSecrets: []

spec:
  labels: {}
  annotations:
    {}
    # Add custom pod annotations here
    # Annotations are converted to a JSON string and run through
    # the helm `tpl` function. Then converted back to a map and
    # rendered as YAML. This allows usage of go template directives
    # in your annotations.

# Add custom deployment labels here
labels: {}

# Whether to use helm2-style selectors.  Note pgbouncer version <= v1.0.10 defined the Deployment spec.template.matchLabels:{} this way,
# so define this to true to upgrade an existing pgbouncer deployment of versions <= v1.0.10.
helm2selector: false

# add key: value map entries to customSettings to be added to pbgouncer.ini [pgbouncer] section
customSettings: {}

# Service configuration
service:
  enabled: true
  type: ClusterIP
  name: ""
  annotations: {}

global:
  # optionally use namespace as dbname
  namespacedDatabases: false

# If this is set, the specified secret is mounted, and
# the client.key is mounted as the key file, client.crt
# is mounted as the tls_cert + tls_ca
clientTLSSecret:

cloudSqlInstance:

environment_variables:
