apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "pgbouncer.fullname" . }}
data:
  {{- range $k, $v := .Values.environment_variables }}
    {{ $k }}: {{ $v | b64enc }}
  {{- end }}
